services:
  db:
    image: postgres:15
    container_name: data_sentinel_db
    restart: always
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel_pass
      POSTGRES_DB: sentinel_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://sentinel:sentinel_pass@db:5432/sentinel_db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  pgdata: