FROM python:3.11

WORKDIR /app

RUN pip install streamlit requests pandas

COPY frontend/ frontend/

WORKDIR /app/frontend

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]